In [3]:
tweet = 'Go Sports! #Sports'
tweet.split('#')[1]

'Sports'

In [10]:
d = {'key1': 'item1', 'key2': 'item2'}
d.items()
#d.keys()

dict_items([('key1', 'item1'), ('key2', 'item2')])

In [29]:
import numpy as np
mylist = [1,2,3,4]
mylist_2 = [[1,2,3],[4,5,6],[7,8,9]]
x = type(mylist)
print(x)
y = type(np.array(mylist))
z = np.array(mylist_2)
a = type(z)
print(z)
print(a)
b = np.arange(0,10,2)
print(b)
c = np.zeros(5)
print(c)


<class 'list'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
[0 2 4 6 8]
[0. 0. 0. 0. 0.]


In [31]:
np.zeros(5)
np.random.rand(5,2)


array([[0.50373358, 0.73639537],
       [0.49691047, 0.72892885],
       [0.97034756, 0.14974975],
       [0.69280669, 0.55413004],
       [0.69604346, 0.9959972 ]])