In [1]:
import numpy as np

In [6]:
#create an array of 10 zeros
import numpy as np
np.zeros(10)
#print(x)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
#create an array of 10 ones
import numpy as np
np.ones(10)
#np.fives(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
#create an array of 10 fives
import numpy as np
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [17]:
#create an array of integers from 10 to 50
import numpy as np
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [18]:
#even integers from 10 to 50
import numpy as np
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [19]:
#create matrix 3x3 values ranging from 0 to 8
import numpy as np
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.random.rand(1)

array([0.2904551])

In [22]:
np.random.randn(25)

array([-0.31230803, -1.53260879,  0.72170417, -0.31443325,  1.6498546 ,
        0.15837584, -0.13339822,  1.01342427,  0.01926765, -0.64468333,
        0.5453312 ,  0.85756789,  0.27211696, -0.57766158, -0.3124931 ,
        0.29997524,  0.79287935, -1.74395014,  1.10287533,  0.1722712 ,
        1.92073844,  1.1657297 ,  0.22842081,  1.72982103, -1.62660285])

In [30]:
#create a matrix 10x10
x = np.arange(1,101)/100
x.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [3]:
#matrix - 20 linearly spaced between 0 - 1 
import numpy as np
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [25]:
# matrix
import numpy as np
mat = np.arange(1,26).reshape(5,5)
#mat[2:,1:]

In [28]:
# matrix
import numpy as np
mat = np.arange(1,26).reshape(5,5)
#mat[2:,1:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [45]:
#mat[3,4]
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [54]:
import numpy as np
ma = np.arange(1,26).reshape(5,5)
#ma[4:]
ma[3:5,:]
ma.sum()
ma.std()
ma.sum(axis=0)

array([55, 60, 65, 70, 75])

In [58]:
np.random.seed(101)
np.random.rand(1)

array([0.51639863])

In [59]:
#indexing and slicing
import numpy as np
x = np.arange(1,26).reshape(5,5)